# Generated by Django 4.2.7 on 2025-07-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("answers", "0001_initial"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="questions.question",
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["question", "is_accepted"], name="answers_questio_dafd07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["author"], name="answers_author__068af8_idx"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["created_at"], name="answers_created_a5b46e_idx"
            ),
        ),
    ]
