# Generated by Django 4.2.7 on 2025-07-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="tags_name_38920e_idx"),
                    models.Index(
                        fields=["usage_count"], name="tags_usage_c_26dec2_idx"
                    ),
                ],
            },
        ),
    ]
