# Generated by Django 5.1.5 on 2025-07-12 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_add_question_fields"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create the QuestionTag through model first
        migrations.CreateModel(
            name="QuestionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("relevance_score", models.FloatField(default=1.0)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tags.tag"
                    ),
                ),
            ],
            options={
                "db_table": "question_tags",
                "unique_together": {("question", "tag")},
            },
        ),
        migrations.AddIndex(
            model_name="questiontag",
            index=models.Index(
                fields=["question", "relevance_score"],
                name="question_ta_questio_938e59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questiontag",
            index=models.Index(
                fields=["tag", "added_at"], name="question_ta_tag_id_90e025_idx"
            ),
        ),
    ]
