# Generated by Django 5.1.5 on 2025-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_copy_tag_relationships"),
        ("tags", "0001_initial"),
    ]

    operations = [
        # Remove the old tags field
        migrations.RemoveField(
            model_name="question",
            name="tags",
        ),
        # Add the new tags field with through parameter
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="questions",
                through="questions.QuestionTag",
                to="tags.tag",
            ),
        ),
    ]
